web:
  restart: always
  build: ./web
  expose:
    - "8080"
  links:
    - api:api

nginx:
  build: ./nginx
  links:
    - web:web
  ports:
    - "80:80"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

api:
  restart: always
  build: ./api
  environment:
    WEB_SETTINGS: /usr/settings/settings.cfg
  ports:
    - "4000:4000"
  volumes:
    - ./api:/usr/src/app/
    - ../settings:/usr/settings/
  links:
    - mongo:mongo
  command: /usr/local/bin/gunicorn -w 2 -b :4000 app:app

mongo:
  build: ./mongo
  command: "--smallfiles"
  volumes:
    - ../mongodb/data/db:/data/db
